hm_4/Models/Admin.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace hm_4.Models
{
    public class Admin
    {
        public int AdminId { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public int Age { get; set; }
        public string City { get; set; }

        
    }
}

hm_4/Models/ErrorViewModel.cs
using System;

namespace hm_4.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

hm_4/Models/MenuContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace hm_4.Models
{
    public class MenuContext : DbContext
    {
        public DbSet<Moderator> ModeratorList { get; set; }
        public DbSet<Admin> AdminList { get; set; }

        public MenuContext(DbContextOptions<MenuContext> options)
            : base(options)
        {
            Database.EnsureCreated();
        }
    }
}

hm_4/Models/Moderator.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace hm_4.Models
{
    public class Moderator
    {
        public int ModeratorId { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public int Age { get; set; }
        public int Experience { get; set; }
    }
}

hm_4/Controllers/AdminsMenuController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.EntityFrameworkCore;

using hm_4.Models;

namespace hm_4.Controllers
{
    public class AdminsMenuController : Controller
    {
        MenuContext db;
        public AdminsMenuController(MenuContext context)
        {
            db = context;
        }

        public async Task<IActionResult> Admins(string searchStr)
        {
            var admins = from i in db.AdminList select i;
            if (!String.IsNullOrEmpty(searchStr))
            {
                admins = admins.Where(s => s.FirstName.Contains(searchStr) ||s.SecondName.Contains(searchStr));
            }
            return View(await admins.ToListAsync());
        }

        public IActionResult InfoAdm(int? id)
        {
            if (id == null) return RedirectToAction("Admins");
            var admin = db.AdminList.Find(id);
            if (admin == null)
                return NotFound();
            return View(admin);
        }


        [HttpGet]
        public ActionResult AddAdm()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddAdm(Admin admin)
        {
            if (db.AdminList.Contains(admin))
            {
                return BadRequest();
            }
            db.AdminList.Add(admin);
            db.SaveChanges();

            return RedirectToAction("Admins");
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null) return NotFound();
            
            Admin adm = db.AdminList.Find(id);

            if (adm != null)
                return View(adm);
            return NotFound();
        }
        [HttpPost]
        public ActionResult Edit(Admin adm)
        {
            db.Entry(adm).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Admins");
        }

        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
                return NotFound();

            Admin adm = db.AdminList.Find(id);
            if (adm == null)
                return NotFound();

            return View(adm);
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var adm = db.AdminList.Find(id);
            if (adm == null)
            {
                return NotFound();
            }
            db.AdminList.Remove(adm);
            db.SaveChanges();

            return RedirectToAction("Admins");
        }

    }
}

hm_4/Controllers/ModeratorsMenuController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.EntityFrameworkCore;

using hm_4.Models;

namespace hm_4.Controllers
{
    public class ModeratorsMenuController : Controller
    {
        MenuContext db;
        public ModeratorsMenuController(MenuContext context)
        {
            db = context;
        }

        public async Task<IActionResult> Moderators(string searchStr)
        {
            var moderators = from i in db.ModeratorList select i;
            if (!String.IsNullOrEmpty(searchStr))
            {
                moderators = moderators.Where(
                    s => s.FirstName.Contains(searchStr) || s.SecondName.Contains(searchStr));
            }
            return View(await moderators.ToListAsync());
        }

        public IActionResult InfoMod(int? id)
        {
            if (id == null) return RedirectToAction("Moderators");
            var moderator = db.ModeratorList.Find(id);
            if (moderator == null)
                return NotFound();
            return View(moderator);
        }

        [HttpGet]
        public ActionResult AddMod()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddMod(Moderator moderator)
        {
            if (db.ModeratorList.Contains(moderator))
            {
                return BadRequest();
            }
            db.ModeratorList.Add(moderator);
            db.SaveChanges();

            return RedirectToAction("Moderators");
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null) return NotFound();
            Moderator mod = db.ModeratorList.Find(id);
            if (mod != null)
            {
                return View(mod);
            }
            return NotFound();
        }
        [HttpPost]
        public ActionResult Edit(Moderator mod)
        {
            db.Entry(mod).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Moderators");
        }

        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
                return NotFound();

            Moderator mod = db.ModeratorList.Find(id);
            if (mod == null)
                return NotFound();

            return View(mod);
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            Moderator mod = db.ModeratorList.Find(id);
            if (mod == null)
            {
                return NotFound();
            }
            db.ModeratorList.Remove(mod);
            db.SaveChanges();

            return RedirectToAction("Moderators");
        }
    }
}

hm_4/Views/AdminsMenu/AddAdm.cshtml
@{
    ViewData["Title"] = "Админы";
}
<h3>Добавление админа</h3>

<form method="post" class="form-horizontal" role="form">
    <p>Для добавления заполните следующие поля:</p>
    <div class="form-group">
        <label for="User" class="col-md-2 control-label">Имя:</label>
        <div class="col-md-4">
            <input type="text" name="FirstName" class="form-control" />
        </div>
    </div>
    <div class="form-group">
        <label for="Address" class="col-md-2 control-label">Фамилия:</label>
        <div class="col-md-4">
            <input type="text" name="SecondName" class="form-control" />
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-2 control-label">Возраст:</label>
        <div class="col-md-4">
            <input type="text" name="Age" class="form-control" />
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-2 control-label">Город проживания:</label>
        <div class="col-md-4">
            <input type="text" name="City" class="form-control" />
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Добавить" />
        </div>
    </div>
</form>

hm_4/Views/AdminsMenu/Admins.cshtml
@model IEnumerable<hm_4.Models.Admin>
@{
    ViewData["Title"] = "Админы";
}
<h3>Админы:</h3>
<form asp-controller="AdminsMenu" asp-action="Admins">
    <p>
        <input type="text" name="SearchStr">
        <input type="submit" value="Поиск" />
    </p>
</form>
<p>
    <a asp-action="AddAdm">Добавить</a>
</p>
<table class="table-condensed" cellpadding="8">
    <tr>
        <td>Имя</td>
        <td>Фамилия</td>
    </tr>
    @foreach (var adm in Model)
    {
        <tr>
            <td>@adm.FirstName</td>
            <td>@adm.SecondName</td>
            <td><a href="~/AdminsMenu/InfoAdm/@adm.AdminId">Инфо</a></td>
            <td><a href="~/AdminsMenu/Edit/@adm.AdminId">Изменить</a></td>
            <td><a href="~/AdminsMenu/Delete/@adm.AdminId">Удалить</a></td>
        </tr>
    }
</table>

hm_4/Views/AdminsMenu/Delete.cshtml
@model hm_4.Models.Admin
@{
    ViewData["Title"] = "Админы";
}
<h2>Удаление админа</h2>
<table class="table-condensed" cellpadding="8">
    <tr>
        <td>Имя</td>
        <td>Фамилия</td>
    </tr>
    <tr>
        <td>@Model.FirstName</td>
        <td>@Model.SecondName</td>
    </tr>
</table>

@using (Html.BeginForm())
{
    <input type="submit" value="Удалить" />
}

hm_4/Views/AdminsMenu/Edit.cshtml
@{
    ViewData["Title"] = "Админы";
}
@model hm_4.Models.Admin
<h2>Админ @Model.FirstName @Model.SecondName</h2>
<form method="post">
    <fieldset>
        @Html.HiddenFor(m => m.AdminId)
        <p>
            @Html.LabelFor(m => m.FirstName, "Имя")
            @Html.EditorFor(m => m.FirstName)

            @Html.LabelFor(m => m.SecondName, "Фамилия")
            @Html.EditorFor(m => m.SecondName)
            <br/>
            @Html.LabelFor(m => m.Age, "Возраст")
            @Html.EditorFor(m => m.Age)

            @Html.LabelFor(m => m.City, "Город проживания")
            @Html.EditorFor(m => m.City)
        </p>
        <p><input type="submit" value="Изменить" /></p>
    </fieldset>
</form>

hm_4/Views/AdminsMenu/InfoAdm.cshtml
@model hm_4.Models.Admin
@{
    ViewData["Title"] = "Админы";
}
<h3>Админ @Model.FirstName @Model.SecondName </h3>
<table class="table-condensed" cellpadding="8">
    <tr>
        <td>Имя</td>
        <td>Фамилия</td>
        <td>Возраст</td>
        <td>Город проживания</td>
    </tr>
    <tr>
        <td>@Model.FirstName</td>
        <td>@Model.SecondName</td>
        <td>@Model.Age</td>
        <td>@Model.City</td>
    </tr>
</table>

hm_4/Views/ModeratorsMenu/AddMod.cshtml
@{
    ViewData["Title"] = "Модераторы";
}
<h3>Добавление модератора</h3>

<form method="post" class="form-horizontal" role="form">
    <p>Для добавления заполните следующие поля:</p>
    <div class="form-group">
        <label for="User" class="col-md-2 control-label">Имя:</label>
        <div class="col-md-4">
            <input type="text" name="FirstName" class="form-control" />
        </div>
    </div>
    <div class="form-group">
        <label for="Address" class="col-md-2 control-label">Фамилия:</label>
        <div class="col-md-4">
            <input type="text" name="SecondName" class="form-control" />
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-2 control-label">Возраст:</label>
        <div class="col-md-4">
            <input type="text" name="Age" class="form-control" />
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-2 control-label">Опыт работы:</label>
        <div class="col-md-4">
            <input type="text" name="Experience" class="form-control" />
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Добавить" />
        </div>
    </div>
</form>

hm_4/Views/ModeratorsMenu/Delete.cshtml
@model hm_4.Models.Moderator
@{
    ViewData["Title"] = "Модераторы";
}
<h2>Удаление админа</h2>
<table class="table-condensed" cellpadding="8">
    <tr>
        <td>Имя</td>
        <td>Фамилия</td>
    </tr>
    <tr>
        <td>@Model.FirstName</td>
        <td>@Model.SecondName</td>
    </tr>
</table>

@using (Html.BeginForm())
{
    <input type="submit" value="Удалить" />
}

hm_4/Views/ModeratorsMenu/Edit.cshtml
@{
    ViewData["Title"] = "Модераторы";
}
@model hm_4.Models.Moderator
<h2>Модератор @Model.FirstName @Model.SecondName</h2>
<form method="post">
    <fieldset>
        @Html.HiddenFor(m => m.ModeratorId)
        <p>
            @Html.LabelFor(m => m.FirstName, "Имя")
            @Html.EditorFor(m => m.FirstName)

            @Html.LabelFor(m => m.SecondName, "Фамилия")
            @Html.EditorFor(m => m.SecondName)
            <br/>
            @Html.LabelFor(m => m.Age, "Возраст")
            @Html.EditorFor(m => m.Age)

            @Html.LabelFor(m => m.Experience, "Опыт работы")
            @Html.EditorFor(m => m.Experience)
        </p>
        <p><input type="submit" value="Изменить" /></p>
    </fieldset>
</form>

hm_4/Views/ModeratorsMenu/InfoMod.cshtml
@model hm_4.Models.Moderator
@{
    ViewData["Title"] = "Модераторы";
}
<h3>Модератор @Model.FirstName @Model.SecondName </h3>
<table class="table-condensed" cellpadding="8">
    <tr>
        <td>Имя</td>
        <td>Фамилия</td>
        <td>Возраст</td>
        <td>Опыт работы</td>
    </tr>
    <tr>
        <td>@Model.FirstName</td>
        <td>@Model.SecondName</td>
        <td>@Model.Age</td>
        <td>@Model.Experience</td>
    </tr>
</table>

hm_4/Views/ModeratorsMenu/Moderators.cshtml
@model IEnumerable<hm_4.Models.Moderator>
@{
    ViewData["Title"] = "Модераторы";
}
<h3>Модераторы: </h3>
<form asp-controller="ModeratorsMenu" asp-action="Moderators">
    <p>
        <input type="text" name="SearchStr">
        <input type="submit" value="Поиск" />
    </p>
</form>
<p>
    <a asp-action="AddMod">Добавить</a>
</p>
<table class="table-condensed" cellpadding="8">
    <tr>
        <td>Имя</td>
        <td>Фамилия</td>
    </tr>
    @foreach (var moder in Model)
    {
        <tr>
            <td>@moder.FirstName</td>
            <td>@moder.SecondName</td>
            <td><a href="~/ModeratorsMenu/InfoMod/@moder.ModeratorId">Инфо</a></td>
            <td><a href="~/ModeratorsMenu/Edit/@moder.ModeratorId">Изменить</a></td>
            <td><a href="~/ModeratorsMenu/Delete/@moder.ModeratorId">Удалить</a></td>
        </tr>
    }
</table>

hm_4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
</head>
<body>
    <!--меню-->
    <nav class="navbar navbar-inverse">
        <div class="container">
            <div>
                <a href="~/AdminsMenu/Admins" class="navbar-brand">Меню админов</a>
                <a href="~/ModeratorsMenu/Moderators" class="navbar-brand">Меню модераторов</a>
            </div>
        </div>
    </nav>
    <!--основной контент-->
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>© 2020 - Mod and Adm menu</p>
        </footer>
    </div>
</body>
</html>